services:
  app:
    build:
      context: java_prodcuer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - consumer_1
      - consumer_2
      - consumer_3
      - consumer_4
      - rabbitmq
    command: ["gradle", "run"]

  consumer_1:
    build:
      context: python_consumer
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      PYTHONPATH: "./"
    command: ["sh", "-c", "sleep 5 && python parallel_consumer/parallel/parallel.py"]
  
  consumer_2:
    build:
      context: python_consumer
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - consumer_1
      - rabbitmq
    environment:
      PYTHONPATH: "./"
    command: ["sh", "-c", "sleep 5 && python parallel_consumer/parallel/parallel.py"]

  consumer_3:
    build:
      context: python_consumer
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - consumer_2
      - rabbitmq
    environment:
      PYTHONPATH: "./"
    command: ["sh", "-c", "sleep 5 && python parallel_consumer/parallel/parallel.py"]

  consumer_4:
    build:
      context: python_consumer
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - consumer_3
      - rabbitmq
    environment:
      PYTHONPATH: "./"
    command: ["sh", "-c", "sleep 5 && python parallel_consumer/parallel/parallel.py"]

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  appnet:
    driver: bridge